/** Unit tests for the PRQL compile wrapper and its error mapper. No database. */
import { describe, expect, it } from "vitest";
import { compilePrql, mapPrqlError } from "#/lib/prql/compile";
import { MAX_SQL_LENGTH } from "#/lib/sql/guard";

describe("compilePrql", () => {
  it("compiles a pipeline to PostgreSQL", async () => {
    const result = await compilePrql(
      "from sellers | filter rating > 4 | take 5",
    );
    expect("error" in result).toBe(false);
    if ("error" in result) return;
    expect(result.sql).toMatch(/SELECT/i);
    expect(result.sql).toMatch(/FROM\s+sellers/i);
    expect(result.sql).toMatch(/WHERE/i);
    expect(result.sql).toMatch(/LIMIT/i);
  });

  it("emits no signature comment", async () => {
    const result = await compilePrql("from sellers | take 1");
    expect("error" in result).toBe(false);
    if ("error" in result) return;
    expect(result.sql).not.toMatch(/Generated by/i);
    expect(result.sql).not.toContain("--");
  });

  it("formats the output across multiple lines", async () => {
    const result = await compilePrql("from sellers | take 1");
    expect("error" in result).toBe(false);
    if ("error" in result) return;
    expect(result.sql.trim().split("\n").length).toBeGreaterThan(1);
  });

  it("targets Postgres by default", async () => {
    // LIMIT is Postgres/ANSI; the mssql target would emit TOP/FETCH instead.
    const result = await compilePrql("from sellers | take 3");
    expect("error" in result).toBe(false);
    if ("error" in result) return;
    expect(result.sql).toMatch(/LIMIT/i);
  });

  it("reports an unknown transform with a 1-based location", async () => {
    const result = await compilePrql("from employees | foo first_name");
    expect("error" in result).toBe(true);
    if (!("error" in result)) return;
    expect(result.error.reason.length).toBeGreaterThan(0);
    expect(result.error.location).not.toBeNull();
    expect(result.error.location?.startLine).toBe(1);
    // The compiler reports 0-based column 17 for `foo`.
    expect(result.error.location?.startColumn).toBe(18);
  });

  it("rejects empty input before reaching the compiler", async () => {
    for (const input of ["", "   \n\t "]) {
      const result = await compilePrql(input);
      expect("error" in result).toBe(true);
      if (!("error" in result)) return;
      expect(result.error.reason).toBe("PRQL query is empty.");
      expect(result.error.location).toBeNull();
    }
  });

  it("rejects over-length input", async () => {
    const result = await compilePrql("a".repeat(MAX_SQL_LENGTH + 1));
    expect("error" in result).toBe(true);
    if (!("error" in result)) return;
    expect(result.error.reason).toContain("too long");
  });

  it("never leaks a stack trace or file path in the error", async () => {
    const result = await compilePrql("from |");
    expect("error" in result).toBe(true);
    if (!("error" in result)) return;
    const serialised = JSON.stringify(result.error);
    expect(serialised).not.toMatch(/\bat\s+\S+\s+\(/);
    expect(serialised).not.toContain("node_modules");
  });
});

describe("mapPrqlError", () => {
  const generic = {
    reason: "Failed to compile PRQL.",
    code: null,
    hints: [],
    display: null,
    location: null,
  };

  it("maps a well-formed compiler payload to 1-based locations", () => {
    const err = new Error(
      JSON.stringify({
        inner: [
          {
            kind: "Error",
            code: "E0001",
            reason: "Unknown name `foo`",
            hints: ["did you mean `from`?"],
            span: "1:17-20",
            display: "annotated snippet",
            location: { start: [0, 17], end: [2, 20] },
          },
        ],
      }),
    );
    expect(mapPrqlError(err)).toEqual({
      reason: "Unknown name `foo`",
      code: "E0001",
      hints: ["did you mean `from`?"],
      display: "annotated snippet",
      location: {
        startLine: 1,
        startColumn: 18,
        endLine: 3,
        endColumn: 21,
      },
    });
  });

  it("keeps the reason when the location is missing", () => {
    const err = new Error(
      JSON.stringify({ inner: [{ reason: "boom", location: null }] }),
    );
    expect(mapPrqlError(err)).toEqual({
      reason: "boom",
      code: null,
      hints: [],
      display: null,
      location: null,
    });
  });

  it("drops a malformed location instead of throwing", () => {
    const err = new Error(
      JSON.stringify({ inner: [{ reason: "boom", location: { start: [0] } }] }),
    );
    expect(mapPrqlError(err).location).toBeNull();
  });

  it("degrades to a generic error for unparseable payloads", () => {
    expect(mapPrqlError(new Error("not json"))).toEqual(generic);
    expect(mapPrqlError(new Error(JSON.stringify({ inner: [] })))).toEqual(
      generic,
    );
    expect(mapPrqlError(new Error(JSON.stringify({})))).toEqual(generic);
    expect(mapPrqlError(undefined)).toEqual(generic);
    expect(mapPrqlError("a string")).toEqual(generic);
  });

  it("filters non-string hints", () => {
    const err = new Error(
      JSON.stringify({ inner: [{ reason: "boom", hints: ["ok", 42, null] }] }),
    );
    expect(mapPrqlError(err).hints).toEqual(["ok"]);
  });
});
